version: '2'
services:
  redis-the-challenge:
    image: redis:3.0.7-alpine
    ports:
      - 6379:6379
    logging:
      options:
        max-size: "100k"
        max-file: "10"
    environment:
      - "TZ=GMT"
    hostname: "redis-the-challenge"
    container_name: the_challenge_redis

  mysql-the-challenge:
    image: mysql:5.6.27
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=thechallenge
      - "TZ=GMT"
    hostname: "mysql-the-challenge"
    command: "/mysql/run.sh"
    logging:
      options:
        max-size: "100k"
        max-file: "10"
    container_name: the_challenge_mysql

  the-challenge:
    build: ./
    depends_on:
      - mysql-the-challenge
      - redis-the-challenge
    ports:
      - 8080:8080
      - 8181:8181
    volumes:
      - ./:/root/thechallenge
    environment:
      - "TZ=GMT"
    hostname: "the-challenge"
    logging:
      options:
        max-size: "100k"
        max-file: "10"
    container_name: the_challenge
